### ISSUE TITLE
Please share performance with thinkbook

### ISSUE THREAD

**Issue by khurshid-alam** [sundarnagarajan/rdp-thinbook-linux#18]
Hi,

We are a small company and thinking of purchasing thinbook. I didn't any video or review regarding this on internet, so I am asking here. I have few questions regarding this:

1) How does it perform with 5-6 tabs opened in firefox/chromium in Ubuntu 17.10? 
2) How does it perform with wine and ms office?
3) Can it play 720p videos from youtube smoothly?
4) Does wi-fi connection drops time-to-time? With the default wifi chipset, Can download speed go over 256 KBps with 4MBps internet connection?
5) Does it heated up after constant usage of 5-6 hours?
7) How is the quality of the keyboard?
8) In forums I heard some charging issues, is it true?
 
It would be nice if you share this with us. Can you upload a video with Ubuntu 17.10 if possible ?

Thank you.

**Comment by sundarnagarajan** [comment]
My github software repository is aimed at helping other owners (or
prospective owners) of the RDP Thinbook run Linux (Ubuntu in particular) on
the RDP Thinbook.

I am *NOT* a reviewer - professional or amateur, of this laptop or others.

Some of your questions appear to be at least partly technical, and I will
try to answer them.

*How does it perform with 5-6 tabs opened in firefox/chromium in Ubuntu
17.10?*


   - It depends on which 'tabs' you are talking about. These 'tabs' are
   often client applications written in Javascript, and can vary in their use
   of network, memory and CPU
   - I know from personal experience that 'applications' like gmail and
   other Google 'web apps' are particularly egregious in memory use. I am sure
   other web apps could be just as bad or worse.
   - In particular, Chromium / Google Chrome tries to use any and all
   available free RAM (provided running web apps need it).
   - I have tried running Google Chrome (Chromium should be pretty similar)
   on the RDP Thinbook with 20+ tabs open as I usually do on my desktop. It
   definitely slows down the entire machine, and opening other applications,
   such as Libre Office, becomes very slow and the problem is immediately
   alleviated by shutting down Google Chrome. *This is a Google Chrome /
   Chromium* problem. If it happens in Firefox also (I have not tested
   Firefox), it is (also) a *Firefox problem*. On lower-powered laptops,
   you should use something like firejail
   <https://github.com/netblue30/firejail> to impose memory use
   restrictions on Google Chrome / Chromium / Firefox. I have not come around
   to writing such a firejail recipe.


*How does it perform with wine and ms office?*

   - I do not use Windows applications and / or MS Office, so I cannot
   answer this.
   - From a technical perspective, I would not expect 'performance' to be
   different from any other laptop of a similar configuration.


*Can it play 720p videos from youtube smoothly?*

   - Youtube works.
   - I do not have the time to qualify this by resolution, codec, video
   container etc


*Does wi-fi connection drops time-to-time? With the default wifi chipset?*

   - With the default built-in Realtek RTL8723BS Wifi chipset,  I have
   found Wifi connection to be remarkably stable in Linux.
   - I have *virtually never* had to restart the wifi because it was
   'hung', 'non-responsive' etc
   - This includes across 1 or 2 cycles of suspend-resume.


*Can download speed go over 256 KBps with 4MBps internet connection?*

   - The answer to this question is: it depends
      - What is a 4 MBps internet connection? Rated, or real? Download or
      upload or both?
      - Which remote Internet service are you accessing?
      - What is between you and the remote Internet service?
         - Which router
         - How much 'buffer bloat'
         - What path does your request take on the Internet (beyond your
         ISP)?
      - Removing all the above factors, connecting between my RDP Thinbook
   over  Wifi through my Asus RT-N16 router running OpenWRT, connecting to
   another Linux box with a 1 Gbps connection, I would say that download speed
   can go over 256 Kbps

*Does it heated up after constant usage of 5-6 hours?*
Not in my observation. I have:

   - Kept it fairly idle for days on end
   - Kept audio playing (uring 'radiotray') for 6 hours+
   - Kept youtube playing for 4 hours+


*How is the quality of the keyboard?*


   - I am not a 'reviewer'


*In forums I heard some charging issues, is it true?*

You should go back to the 'forums' and get a more *precise and
technical* representation
for your question.

I have *no issues* in the following:

   - Connect AC adapter when battery is not 100% charged - battery starts
   to charge
   - Keep AC adapter connected - battery charge increases up to 100%
   - Linux driver senses:
      - Whether AC adapter is connected or not
      - What is the current battery charge level
      - Whether battery is charging or fully charged
      - Some statistical prediction of:
         - Time to full
         - Time to empty

**Comment by khurshid-alam** [comment]
Thank you for your time and clear explanation. I appreciate your help.

>  - Youtube works.

Ok. This will do.

>    - With the default built-in Realtek RTL8723BS Wifi chipset,  I have
>    found Wifi connection to be remarkably stable in Linux.
>    - I have *virtually never* had to restart the wifi because it was
>    'hung', 'non-responsive' etc
>    - This includes across 1 or 2 cycles of suspend-resume.

Alright. Thanks.

>    - The answer to this question is: it depends
>       - What is a 4 MBps internet connection? Rated, or real? Download or
>       upload or both?
>       - Which remote Internet service are you accessing?
>       - What is between you and the remote Internet service?
>          - Which router
>          - How much 'buffer bloat'
>          - What path does your request take on the Internet (beyond your
>          ISP)?

Flat 4MBps connection. I was talking about the speed when downloading ubuntu.iso from ubuntu.com.
