### ISSUE TITLE
problem_mean_while_installing

### ISSUE THREAD

**Issue by praveen48972** [sundarnagarajan/rdp-thinbook-linux#19]
![1 first_error_msg](https://user-images.githubusercontent.com/34230756/33541092-d400c1c2-d8f3-11e7-8408-f32e5feaf428.jpg)
![2 nd_error_msg](https://user-images.githubusercontent.com/34230756/33541093-d4748990-d8f3-11e7-9092-33ac7272a3ec.jpg)

these are error msgs....
I am new to the Linux......

Answer 1&2.  I used pre-compiled remastered xubuntu 16.04.3  ISO

Answer 3. I was installing a clean installation to SSD, 

Question 4: 4.While partitioning your target disk during installation, did you create (and use) a GPT partition table and an EFI partition? (this question I dint get properly,, because I am new with linux)

**Comment by sundarnagarajan** [comment]
If you are new to Linux, the best advice I can give you is the following:

- To start with do not try to INSTALL to hard disk
- Try using the ISO as a LIVE Linux environment - will help you learn Linux, so that you are no longer new to Linux
- In the Live Linux environment, you get EVERYTHING, except your session changes will not be saved
- Once you get the hang of Linux, you can first learn to add an SD card as additional storage, where you can store the work that you do
- Once you get this far, you can then try installing to SSD.

**Comment by praveen48972** [comment]
Ok sir,,,
thank you

**Comment by praveen48972** [comment]
I used this whole day ......its awsome plese sir make a video tutorial for installling this pleeeeeeeeeeeeeeeeeeeeeese sir..........

**Comment by praveen48972** [comment]
Sir ,,I have installed this on USB Flash with  persistency ...
