### ISSUE TITLE
Please use Ubuntu's default kernel

### ISSUE THREAD

**Issue by khurshid-alam** [sundarnagarajan/rdp-thinbook-linux#21]
Ubuntu's kernel uses some apparmor patches for Unity. Without it many things won't work as expected.

Ubuntu's kernel source is available at : https://launchpad.net/ubuntu/+source/linux

You can get the source locally by using d-get, then you can patch it and upload it to a ppa.

For example,
Kernel 4.14.x: 

```
dget -x https://launchpad.net/ubuntu/+archive/primary/+files/linux_4.14.0-11.13.dsc
dpkg-source -x linux_4.14.0-11.13.dsc
```

Thanks.

**Comment by sundarnagarajan** [comment]
'many things won't work as expected'


What are these 'many things'? Any links?

Ubuntu's kernel source is available at : https://launchpad.net/ubuntu/+
source/linux

​​

I see a PPA with numerous ubuntu binary packages. Did not find Ubuntu's
patch set

When I look here <http://kernel.ubuntu.com/~kernel-ppa/mainline/>, I find
mainline kernel sources with Ubuntu patches for each kernel version. For
example 4.14.6 <http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.14.6/> is
kernel source + Ubuntu patches for latest 4.14.6 kernel.

I looked at the patches in this directory (in a very cursory way).

0001-base-packaging.patch
<http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.14.6/0001-base-packaging.patch>
:


   - Does not seem to contain anything related to apparmor
   - Name also seems to indicate it is related to 'packaging'

0002-UBUNTU-SAUCE-add-vmlinux.strip-to-BOOT_TARGETS1-on-p.patch
<http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.14.6/0002-UBUNTU-SAUCE-add-vmlinux.strip-to-BOOT_TARGETS1-on-p.patch>
​
<http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.14.6/0002-UBUNTU-SAUCE-add-vmlinux.strip-to-BOOT_TARGETS1-on-p.patch>
​
<http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.14.6/0002-UBUNTU-SAUCE-add-vmlinux.strip-to-BOOT_TARGETS1-on-p.patch>
:​


   - Adds a vmlinux.strip build target

0004-UBUNTU-SAUCE-no-up-disable-pie-when-gcc-has-it-enabl.patch
<http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.14.6/0004-UBUNTU-SAUCE-no-up-disable-pie-when-gcc-has-it-enabl.patch>
:


   - Disables a compilation flag in the Makefile - nothing related to
   AppArmor

​
AppArmor wiki is located at
http://wiki.apparmor.net/index.php/Main_Page
​​
​
O
​n 'kernel' section <http://wiki.apparmor.net/index.php/Main_Page#Kernel>
of this page I see:

AppArmor is in the upstream kernel as of 2.6.36


​I found AppArmor Launchpad project at
https://launchpad.net/apparmor
​​

Downloading latest version of AppArmor from here (
apparmor-2.11.95.tar.gz
​ <https://launchpad.net/apparmor>), I looked at the kernel patches inside.
Under *kernel-patches/v4.14* directory:

0001-UBUNTU-SAUCE-apparmor-af_unix-mediation.patch
README

The README says:

This series is based on what is currently in linux-next scheduled for
inclusion in 4.14

af_unix-mediation is the last remaining patch that is out of tree

​

So there is a single patch that can be applied. I will add this to the set
of patches I use.

Note that the rdp-thinbook-linux uses another github repository that I
created - kernel_build <https://github.com/sundarnagarajan/kernel_build> -
to do the following:

   - ​Download latest *vanilla*, *stock* stable ​
   ​
   ​kernel from kernel.org using the JSON API
   <https://www.kernel.org/releases.json>
   - ​Apply patches allowing some patches to be marked as optional.
   Currently I apply the following patches:

   - Patch to get rfkill to enable RTL 8723bs bluetooth - mandatory
      - Patch to silent logspam from RTL8732bs Wifi driver - has hit
      4.15rc2 - optional, will remove once 4.15 is released
      - ​Upgrade kernel .config automatically selecting any new drivers as
   modules where possible, and using default option (Y/N) when driver cannot
   be a module
   - Check and ensure some kernel driver settings
   - Build the kernel and package as DEB​


​rdp-thinbook-linux ​can only work (properly with all devices working) with
kernel 4.12 onwards. See kernel_config.md
<https://github.com/sundarnagarajan/rdp-thinbook-linux/blob/master/kernel_config.md>
:

   - ​Wifi support (RTL8723bs) came in 4.12
   - Sound support (ES8316) 14-inch RDP Thinbook ​came in 4.13


There are no 4.13 kernels that are currently supported (as listed on
kernel.org).

So that leaves just 4.14+ kernels.
Once the single AppArmor patch for 4.14 hits the mainline kernel, I can
delete the patch.



​

**Comment by sundarnagarajan** [comment]
That patch does not apply cleanly on 4.14.6 (latest kernel). Parts of the patch seem to be already present in the kernel source:

    ```diff --git a/security/apparmor/af_unix.c b/security/apparmor/af_unix.c
    new file mode 100644```

Other parts of the patch fail.
Output of patch_and_build_kernel.sh:

```
    checking file security/apparmor/Makefile
    Hunk #1 FAILED at 4.
    1 out of 1 hunk FAILED
    checking file security/apparmor/af_unix.c
    checking file security/apparmor/apparmorfs.c
    Hunk #2 succeeded at 2214 (offset -1 lines).
    checking file security/apparmor/file.c
    Hunk #2 succeeded at 289 (offset -1 lines).
    checking file security/apparmor/include/af_unix.h
    can't find file to patch at input line 866
    Perhaps you used the wrong -p or --strip option?
    The text leading up to this was:
    --------------------------
    |diff --git a/security/apparmor/include/net.h b/security/apparmor/include/net.h
    |index 140c8efcf364..0ae45240c352 100644
    |--- a/security/apparmor/include/net.h
    |+++ b/security/apparmor/include/net.h
    --------------------------
    File to patch: 
    Skip this patch? [y] 
    Skipping patch.
    2 out of 2 hunks ignored
    checking file security/apparmor/include/path.h
    checking file security/apparmor/include/policy.h
    Hunk #1 FAILED at 226.
    1 out of 1 hunk FAILED
    checking file security/apparmor/lsm.c
    Hunk #2 FAILED at 783.
    Hunk #3 FAILED at 850.
    Hunk #4 FAILED at 864.
    Hunk #5 FAILED at 877.
    Hunk #6 FAILED at 892.
    Hunk #7 FAILED at 929.
    Hunk #8 FAILED at 955.
    Hunk #9 FAILED at 1010.
    Hunk #10 FAILED at 1138.
    9 out of 10 hunks FAILED
    can't find file to patch at input line 1178
    Perhaps you used the wrong -p or --strip option?
    The text leading up to this was:
    --------------------------
    |diff --git a/security/apparmor/net.c b/security/apparmor/net.c
    |index 33d54435f8d6..dd1953b08e58 100644
    |--- a/security/apparmor/net.c
    |+++ b/security/apparmor/net.c
    --------------------------
    File to patch: 
    Skip this patch? [y] 
    Skipping patch.
    6 out of 6 hunks ignored
```

**Comment by sundarnagarajan** [comment]
That being said, people are free to build and install a kernel of their choice. Procedure is as follows:

* Clone (or fork) rdp-thinbook-linux
* Change make_rdp_iso.sh as follows:
      * Comment out lines cloning kernel_build in function update_from_git
      * Change function compile_kernel to compile kernel debs in some other way
      * Within compile_kernel function move all kernel DEB files to rdp-thinbook-linux/remaster/chroot/kernel-debs/
* Test and use
* If you have forked the repository **AND have tested to make sure everything works on the RDP Thinbook**, open an issue, and I will put a link to your repository.
* Note (repeat): Unless tested on an RDP Thinbook (other machines do not count, since this repository is specifically about the RDP Thinbook), I will not consider it.

**Comment by khurshid-alam** [comment]
@sundarnagarajan 

Yes some patches has been merged with Ubuntu's mainline kernel. Note Debian also use apparmor and both have same sort of patches.

See details of Jhon's branch here:
https://git.kernel.org/pub/scm/linux/kernel/git/jj/linux-apparmor.git/log/?h=for-security

John's also trying to merge new AppArmor development into the mainline
Linux kernel. See thread from April: https://lists.ubuntu.com/archives/apparmor/2017-April/010677.html

It's kinda unorganized and scattered all over the place. That's why I proposed to use Ubuntu's kernel direct from launchpad source because that's the one they used in the official iso.


Btw, I believe If I apply these patches from https://github.com/sundarnagarajan/kernel_build/tree/master/patches
to 4.14.x, we should be fine. No? Correct me if I wrong.

**Comment by sundarnagarajan** [comment]
Both the patches in my build_kernel repository
<https://github.com/sundarnagarajan/kernel_build/tree/master/patches> will
apply and work fine on 4.14 (also 4.13.x). I cannot use "Ubuntu's kernel",
because:

   - Their patches are not very well organized, so that one can see whet
   they are patching and why
   - They have not moved to 4.14 yet - even for Bionic

Empirically (just my own personal experience), I have been using
self-compiled *stock vanilla* kernel from kernel.org for more than 18
months (since 4.1.x or so) on a desktop machine, multiple physical servers
and multiple VPS machines on Digital Ocean with no bad experiences
whatsoever.

Debian has been late to adopt AppArmor (appplying kernel patches as well as
enabling / supporting userspace tools), just as Debian always seems to be
(slow) with adopting everything. I like Debian and SPI, but for anything
other than simplistic servers, Debian is too restrictive. On the desktop,
Debian is just a disaster - Debian Jessie stable cannot detect and use
Intel Graphics which requires no closed source driver at all! And to my
knowledge, Debian by default ships with a 3.x kernel!

**Comment by khurshid-alam** [comment]
I got the kernel source(4.14) using dget and applied your patches.It compiles and works well. I will create a ppa soon and comment here.

**Comment by sundarnagarajan** [comment]
What is dget?

Did you create your PPA?
If you can write a **script** or a **clear set of steps / commands** to do the following, I will be happy to try it out and if it works, I can provide it as an option:
- Pull **mainline kernel** from kernel.org - **not** from some other PPA
- Apply a set of patches, in a specific order
        - Some patches can be marked as mandatory (script fails if patch fails)
        - Some patches can be marked as optional (script does not fail if patch fails)
- Set of patches to use should be clearly derivable from the kernel version
- Desirable features:
        - Patch should include some description of what is being patched and why
        - Patch should have been submitted upstream - either to linux kernel or at least to Ubuntu
        - Patch set should have a **maintainer** that tests, reviews and modifies patches for newer kernels

**Comment by sundarnagarajan** [comment]
Closed because:
- No link to any PPA created
- No response to points above
- I do not see a perceived benefit to using Ubuntu kernels - my trivial patch and automatic configuration and compilation scripts for stock kernels are working well

**Comment by khurshid-alam** [comment]
Sorry for late reply. I did not get any notification until now.

**Ubuntu kernel is necessary because of some apparmor patches which is required for Ubuntu system-wide proxy and for unity.** If you are running Ubuntu and using Ubuntu proxies without apparmor patches, then you are taking huge security risk. **Please do not advertise using kernel from other source in Ubuntu.**

dget is the easiest way to get the source from launchpad and push it git branch. A automatic recipe can be created which can compile the kernel on launchpad automatically when it will detect any change.

The reason I didn't create the ppa because the patch didn't apply cleanly.

For 18.04 all kernels are listed here:
https://launchpad.net/ubuntu/bionic/+source/linux

You can get the source using
```sh
dget -x https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/linux/4.15.0-25.27/linux_4.15.0-25.27.dsc
dpkg-source -x linux_4.15.0-25.27.dsc
cd linux_4.15.0-25.27
#try applyiing patches , Does it work for you?
git add -A
git commit -m "Applying rdp patches"
git remote add launchpad lp:~username/linux/+git/rdp
git push launchpad master
```

Then it will show on your launchpad branch. You can create a recipe from there.

**Comment by sundarnagarajan** [comment]
> **Ubuntu kernel is necessary because of some apparmor patches which is required for Ubuntu system-wide proxy and for unity**. If you are running Ubuntu and using Ubuntu proxies without apparmor patches, then you are taking huge security risk. 

Without trustworthy references, this is simply a laughable statement. I consider myself reasonably educated on security matters, and I choose to consider this a troll, unless you can provide proof. 

Request you not to waste your time and mine in the future by making flippant statements like this. **Consider you have been warned.**

**Comment by khurshid-alam** [comment]
You can see apparmor patches for kernel [here](https://bazaar.launchpad.net/~ubuntu-branches/ubuntu/trusty/apparmor/trusty/files/head:/kernel-patches/3.9/), Since 4.7 most of them are in [ubuntu-upstream](https://lists.ubuntu.com/archives/apparmor/2017-April/010677.html) or in mainline kernel.

Ubuntu has patches for snaps. Atm, in debian sid apparmor is disabled and that's why snapd doesn't work [there](https://forum.snapcraft.io/t/snapd-2-27-6-2-in-debian-sid-blocked-on-apparmor-in-kernel-4-13-0-1/).

Unity doesn't work outside Ubuntu exactly because of these. 

And If I troll why would I do it in your issue tracker? There are many other places to do that.

**Comment by sundarnagarajan** [comment]
1. Unity is not being developed (by Canonical) any more
2. Bionic Beaver onwards, Ubuntu does not ship with Unity as default desktop
3. Unity (desktop) has **NOTHING** to do with apparmor - which is a kernel mechanism for application confinement. If you think differently, provide proof
4. See [discussion on snapcraft.io forums](https://forum.snapcraft.io/t/snapd-vs-upstream-kernel-vs-apparmor/1704/17) on snapd dependency on Ubuntu apparmor patches. Turns out (read the forum discussion) that not all Ubuntu apparmor patches have made it upstream, and Ubuntu's snapd chooses to detect whether it is running on Ubuntu kernel or 'other' (upstream stock) kernel
5. **I DO NOT** consider snapd and in particular snapd **confinement** a priority - and **in particular** I do not consider it as high a priority as making all the hardware work - e.g. Bluetooth and sound.
6. System-wide proxies **have nothing to do with apparmor patches**. If you think differently, provide proof
7. **Vast majority of server applications that use apparmor** work perfectly with upstream (stock) kernels. I have been using stock kernels on Ubuntu and running server applications that have apparmor policies defined for more than 2 years with no issues. So far it is **snapd** that is affected - for the reason above
8. A variety of desktop environments are not available in Debian, not just Ubuntu. See [Other desktop environments not available in Debian include Unity (1 2), Pantheon, ROX, Equinox/EDE, Étoilé, CDE, Artemis, Durden, Trident, Lumina and others.](https://wiki.debian.org/DesktopEnvironment#Desktop_Environment) 
9. The attempt to support Unity in Debian (ayatana) is discussed in [this bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=609278). There is **zero mention** of apparmor
10. I do not want me or the other users of my repository to be confined to the kernels that Ubuntu releases. New kernel versions are released every 8 weeks or so with support for new hardware, new kernel optimizations and fixes for security vulnerabilities. These are more important **to me** than snapd
11. For the **last time** - this repository is about remastering an Ubuntu ISO to support RDP laptops (and other Cherry Trail laptops), and making all the hardware work. At this point in time, to make Bluetooth work, we **need** a patched kernel. **NO STANDARD UBUNTU KERNEL** will work to make Bluetooth work.
12. As I have indicated in my [comment dated Dec-14-2017](https://github.com/sundarnagarajan/rdp-thinbook-linux/issues/21#issuecomment-351831027), all my sources are in this repository (and other referenced repositories. You can fork the repo and see whether you can create an ISO that allows all hardware to work, while using an Ubuntu kernel with all Ubuntu apparmor patches (including those that are not yet upstream). If so, and if you send me a pull request, I will consider it. Until then, **consider this topic closed**.

**Comment by khurshid-alam** [comment]
>1. Unity is not being developed (by Canonical) any more

Canonical still maintains with with community. Until 2021. In 18.04 you can get unity by `sudo apt-get install ubuntu-unity-desktop`

>4. ....

Upstream is basically here is ubuntu upstream. http://kernel.ubuntu.com/git/. Mainline kernel is different.

>5. I DO NOT consider snapd and in particular snapd confinement a priority - and in particular I do not consider it as high a priority as making all the hardware work - e.g. Bluetooth and sound.

Even if you do not consider, snap won't work in custom build kernel or simply run un-confined. And Ubuntu ships snaps by default in Ubuntu. May be you should mention that in Readme.

>6.System-wide proxies have nothing to do with apparmor patches. If you think differently, provide proof

Snap uses ubuntu system-wide proxies for certain cases and apparmor has rules for nssswitch etc.  And ubuntu-system-wide proxies is for [Ubuntu's only](https://bazaar.launchpad.net/~ubuntu-desktop/gnome-control-center/ubuntu/view/head:/debian/patches/92_ubuntu_system_proxy.patch). 

I am sorry I am not going to proof for every little discussion. The source-code is open you can check it for yourself. Or ask apparmor devel mailing list whether using custom kernel in Ubuntu is good idea is not.

>9. The attempt to support Unity in Debian (ayatana) is discussed in this bug report. There is zero mention of apparmor

It happened in irc. Debian declined to have Unity apparmor patches. 


I see this discussion is not going anywhere. I have involved in debian/Ubuntu for more than 12 years. So I know the history but I can't provide proof which happened 7 years ago. If you don't want to support ubuntu kernel that's alright. I am not forcing anything to you.

I will probably open a PR (if I get time) with separate branch with all rdp patches (including bluetooth) which will apply correctly on Ubuntu-Kernels (>= 4.14.x)

Thanks.

**Comment by sundarnagarajan** [comment]
This "issue" and related discussion is going nowhere very fast.

> Canonical still maintains with with community. Until 2021. In 18.04 you can get unity by sudo apt-get install ubuntu-unity-desktop

Mark Shuttleworth, founder of Ubuntu and Canonical [announced on Apr-05-2017](https://blog.ubuntu.com/2017/04/05/growing-ubuntu-for-cloud-and-iot-rather-than-phone-and-convergence) that "I’m writing to let you know that we will end our investment in Unity8, the phone and convergence shell. We will shift our default Ubuntu desktop back to GNOME for Ubuntu 18.04 LTS."

> And  Ubuntu ships snaps by default in Ubuntu

None of the **default applications** shipped with Ubuntu are snaps. None of the applications installed from the default Ubuntu repositories are snaps. Snaps are a totally separate repository.

> Snap uses ubuntu system-wide proxies for certain cases and apparmor has rules for nssswitch etc. 

Snapd uses parts of apparmor that Ubuntu has not merged upstream. Apparmor (part merged upstream) works without an Ubuntu-specific kernel. The link contains a code diff that has nothing to do with apparmor. 

> It happened in irc. Debian declined to have Unity apparmor patches.

IRC is logged. If it really 'happened in irc', IRC logs would be available. When we are too lazy to provide links, it is difficult to have a discussion.

> I  have involved in debian/Ubuntu for more than 12 years. 

Poor justification when you do not choose to spend your time to share person-independent links.
I have been "involved" in Linux (Yggdrasil, Slackware, Red Hat, Mandrake, Ubuntu) since 1993. Enough said.

I don't have the time to continue this pointless debate. My next repsponse will only be if and when I receive a working PR. The last time I heard you were going to create a PPA was in Dec-2017. So I am not holding my breath.
