### ISSUE TITLE
RESOLVED:error boot.

### ISSUE THREAD

**Issue by roboso** [sundarnagarajan/rdp-thinbook-linux#27]
hello I have a mediacom '11 I tried your iso, but it gives me an error:
error: invalid magic number 

then it returns a strange code in any case it does not work the boot

do you have any idea what a mistake it may be?

**Comment by roboso** [comment]
rereading the guide, I saw that you propose an option different from the one I use with dd, I recreated the usb, now charged but ends inexorably in the busybox and from there I do not know what to do.

**Comment by sundarnagarajan** [comment]
What is the mediacom '11 ? Can you send a link that shows the specifications?

What strange code did it return?
Which ISO did you use?

Could not understand this at all: 'ecreated the usb, now charged but ends inexorably in the busybox'

**Comment by roboso** [comment]
What is the mediacom '11 ? Can you send a link that shows the specifications?

System:    Host: diego Kernel: 4.15.0-041500rc4-generic x86_64 bits: 64
           Console: tty 0 Distro: Ubuntu 17.10
Machine:   Device: laptop System: Mediacom product: SmartBook 130 FullHD - M-SB130 serial: N/A
           Mobo: N/A model: N/A serial: N/A
           UEFI: American Megatrends v: Mediacom12x.WJ313O.NHNKREN02 date: 07/27/2017
CPU:       Quad core Intel Atom x5-Z8350 (-MCP-) cache: 1024 KB
           clock speeds: max: 1920 MHz 1: 1176 MHz 2: 1167 MHz 3: 1068 MHz
           4: 1180 MHz
Graphics:  Card: Intel Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series PCI Configuration Registers
           Display Server: X.org 1.19.5 driver: i915
           tty size: 80x24 Advanced Data: N/A for root
Audio:     Card-1 bytcht-es8316 driver: bytcht-es8316
           Card-2 Intel HDMI/DP LPE Audio driver: HdmiLpeAudio
           Sound: ALSA v: k4.15.0-041500rc4-generic
Network:   Card: Failed to Detect Network Card!
Drives:    HDD Total Size: NA (-)
           ID-1: /dev/mmcblk0 model: N/A size: 30.9GB
           ID-2: /dev/mmcblk2 model: N/A size: 7.9GB
Partition: ID-1: / size: 28G used: 12G (43%) fs: ext4 dev: /dev/mmcblk0p2
RAID:      No RAID devices: /proc/mdstat, md_mod kernel module present
Sensors:   System Temperatures: cpu: 67.0C mobo: N/A
           Fan Speeds (in rpm): cpu: N/A
Info:      Processes: 256 Uptime: 3:31 Memory: 2092.3/3877.4MB
           Client: Shell (sudo) inxi: 2.3.37 






What strange code did it return?   
error: invalid magic number

Which ISO did you use?
slak 64 and ubuntu 17.10

**Comment by sundarnagarajan** [comment]
I haven't seen this error before.

Googling for 'linux invalid magic number error'  throws up numerous results.
Examples:
    [linuxquestions.org](https://www.linuxquestions.org/questions/slackware-installation-40/grub2-returns-a-invalid-magic-number-error-when-booting-slackware-13-0%27s-kernel-759604/#post3892179)
    [bbs.archlinux.org](https://bbs.archlinux.org/viewtopic.php?pid=1390888#p1390888)
    [ask.fedoraproject.org](https://ask.fedoraproject.org/en/question/70659/invalid-magic-number-you-need-to-load-the-kernel-first/)

I would try creating the USB bootable disk again. **BUT** if you have already tried two distributions and get the same error, I can only think that you have a bad USB disk or you have perhaps made changes to the ISO (e.g. removed kernel / changed kernel filename / changed grub.cfg)?

### Unsolicited advice: 

You seem to have an Intel Atom x5-Z8350 (Intel Cherry Trail). Some of the onboard devices will not be properly detected and will not work without a custom kernel and some additional scripts. You can try remastering the Ubuntu ISO (for now use only Ubuntu 16.04 LTS) or try some of the pre-built ISOs I have listed on my repo. With the (slightly) modified kernel and additional systemd scripts, you may get Wifi, Bluetooth, Sound working.

See:
* [kernelconfig.md](https://github.com/sundarnagarajan/rdp-thinbook-linux/blob/master/kernel_config.md)
* My [kernel_build repo](https://github.com/sundarnagarajan/kernel_build) that I use in this repo
* [Patches that I apply](https://github.com/sundarnagarajan/kernel_build/tree/master/patches)
* In particular [patch to make bluetooth work](https://github.com/sundarnagarajan/kernel_build/blob/master/patches/001_rfkill_bluetooth_rtl8723bs_bt.patch)
* **ALSO Note** that you will need the [rtk8723bs_bt driver by Larry Finger](https://github.com/lwfinger/rtl8723bs_bt.git) and the [udev rules in my repo](https://github.com/sundarnagarajan/rdp-thinbook-linux/tree/master/remaster/chroot/r8723bs-bluetooth/hardware/bluetooth/scripts) to make Bluetooth work properly
* For the ES8316 sound card, you **may** need the [UCM files from my repo](https://github.com/sundarnagarajan/rdp-thinbook-linux/tree/master/remaster/chroot/sound/hardware/sound/UCM/bytcht-es8316)
* If you are using Ubuntu 17.10, due to a [bug in the newer version of Pulseaudio](https://www.spinics.net/lists/alsa-devel/msg60962.html), you will need to blacklist - see [rdp-sound-blacklist-hdmi.conf](https://github.com/sundarnagarajan/rdp-thinbook-linux/blob/master/remaster/chroot/sound/hardware/sound/rdp-sound-blacklist-hdmi.conf) - see [issue 10](https://github.com/sundarnagarajan/rdp-thinbook-linux/issues/10)

**Comment by roboso** [comment]
but the distosions that I suggest in the guide are not already remastered?

**Comment by sundarnagarajan** [comment]
If you mean the distro ISo's that I have linked in my repo - yes they are all remastered, and should work. They have been tested, by me and others (at least on the RDP Thinbook).

If your machine supports UEFI boot, try the UEFI boot. 
With My ISO, if that works, but non-UEFI does not **AND** your machine supports non-UEFI (legacy / MBR) boot (**very unlikely**), open a separate bug.

**Comment by roboso** [comment]
![img_20171222_232531](https://user-images.githubusercontent.com/6564204/34325460-70b3539c-e892-11e7-8fc4-27488628f73d.jpg)
![img_20171222_232756](https://user-images.githubusercontent.com/6564204/34325461-70e14a40-e892-11e7-8882-69c1adcdd1a0.jpg)

**Comment by sundarnagarajan** [comment]
Posting pictures is not a very productive way of communicating.

The first picture **seems** to indicate you are choosing a UEFI boot - this is correct.
The second picture (**blurred**) seems to show a Busybox error that **usually** occurs if the ```root=/dev/mypartition``` on the kernel command line is wrong in grub.cfg. This error should **NOT** occur when using any of my pre-remastered ISOs to boot into the Live CD - I have tested all pre-remastered ISOs quite well.

Unfortunately, after several rounds of information exchange, I am still not clear about the following:

* Are you using a pre-remastered ISO that I have linked on my repo?
* If YES, what is the NAME of the ISO (**not** the URL)
* What was the [reference to slak64](https://github.com/sundarnagarajan/rdp-thinbook-linux/issues/27#issuecomment-353654395)? I do not have any slackware ISOs listed
* Are you booting into the ```Use Ubuntu without installing``` menu entry - this is the **ONLY** boot sequence that I actually test.

Rest of the questions ASSUME you are using a pre-remastered ISO that I have linked on my repo and **are using the ISO without making any changes**.

* What command did you use to write the ISO to USB drive?
    * Note that the extra arguments to ```dd``` that I provide as an example - ```bs=128k status=progress oflag=direct``` are **NOT** critical to the write operation. If you do **NOT** use the ```oflag=direct``` option, you should perform ```sync``` after writing the ISO and before ejecting the disk. The ```bs=128k``` is just specifying buffer size and can be omitted. The ```status=progress``` asks dd to emit progress messages, and can be ignored (will not be accurate anyway unless you use ```oflag=direct```).
* Best and most important debug activities would probably be:
    * Try writing the ISO AGAIN, using the command I provided **OR** just a simple dd command ```sudo dd if=/path/to/remastered.iso of=/dev/mydisk``` followed by ```sync```
    * Try writing the ISO to a **DIFFERENT** USB disk

**Comment by roboso** [comment]
I solved:

1) use sudo dd if = modified.iso of = $ DEV bs = 128k status = progress oflag = direct && sync
2) removal micro sd card ...

the problem was the micro sd card, with the one inserted probably confused something, honestly I did not test to see what.

Anyway everything works perfectly even the audio.


Thank you very much

**Comment by sundarnagarajan** [comment]
You're most welcome! If you find anyone else using the same or similar laptop (anything with an Intel Cherry Trail SoC showing up as Intel Atom x5-Z8350 or x5-Z8300), you can suggest my repository to them.
