### ISSUE TITLE
Support for RDP Thinbook 1430-EC-1

### ISSUE THREAD

**Issue by khurshid-alam** [sundarnagarajan/rdp-thinbook-linux#32]
The new [1430-EC-1](https://www.amazon.in/RDP-ThinBook-1430-EC1-Ultraslim-Metallic/dp/B0788VKCZS/ref=pd_sbs_147_1?_encoding=UTF8&psc=1&refRID=JTBQCBHRXPYPQPB80FNZ) has a gorgeous lcd display. Intel Quad Core Processor (Up to 1.92 GHz, x5-Z8350). There is also a linux version [1430-ECL](https://www.amazon.in/dp/B079W4VLYB/?coliid=IMMFWNGT8ZN9B&colid=WPCS5R8NRUS&psc=0&ref_=lv_ov_lig_dp_it), but I think the display on Ec-1 is better. Check youtube review here: https://www.youtube.com/watch?v=RMg8ArXulvk

I tried your custom iso (Ubuntu 17.10) on ec-1. It works for most part except Bluetooth and touchpad.

I also tried 18.04 from repo and it also works except touchpad. I don't have ECL, but I believe both are similar product and if we can copy exact bios settings from ECL to EC-1, everything in EC-1 will work too.

So if you can get hands on these device please test and add support for them.

Thank you.

**Comment by sundarnagarajan** [comment]
Interesting. I never heard about the 1430-ECL from RDP - I have just written to them.
Touchpad not working is EXTREMELY strange. Never had that issue on any of the earlier models. Also, since they are selling the ECL model with Linux pre-installed, I am SURE touchpad MUST work.

Bluetooth with an out-of-the-box Ubuntu ISO (standard Ubuntu kernel) is unlikely to work because it needs a 1-line kernel patch which is not upstream (and the patch will not be accepted upstream because they are working on the right place to put the change).

Regarding my custom 17.10 ISO - need to explore further - and I don't have an ECL model. 

I am visiting India in May and I may try to get an ECL model or see if they have an office nearby where I can try an ISO and debug.

**Comment by khurshid-alam** [comment]
ECL and EC-1 are both new models. I have fixed the amazon link above.

**Comment by sundarnagarajan** [comment]
The 1430-ECL is (to my knowledge) the same as the original 1430 sold with Linux pre-installed.
I will check with the RDP folks about what the 1430-EC-1 and 1340 EC-L are and update my main page.

**Comment by khurshid-alam** [comment]
As per my knowledge 1430-ECL is a new model  which has x5-Z8350 (Up to 1.92 GHz, ) , a thin bazel and a superior display. I tried 18.04 on 1430-EC1. It works except for touchpad and Bluetooth. I will try with newer kernel, but atm I am travelling so it has to wait.
