### ISSUE TITLE
not installed properly

### ISSUE THREAD

**Issue by mepradeepkr** [sundarnagarajan/rdp-thinbook-linux#8]
installation stopped and this msg pop up....plz help

The 'grub-efi-ia32', package failed to install into /target/ , without GRUB boot loader, the installed system will not boot.

**Comment by sundarnagarajan** [comment]
Sorry for the delay.
Please provide a few more details:

A. Did you use one of the pre-compiled remastered ISOs? If so, which one?

B. If you remastered your own ISO, what was the source ISO (distribution, version, 32-bit or 64-bit)?

C. Did you install on to the main SSD or to an external (USB) medium?

D. While partitioning your target disk during installation, did you create (and use) an EFI partition?

E. Normally, grub-efi-ia32 package should NOT be installed - what should be installed is grub-efi-ia32-bin. Are you sure the error message referenced 'grub-efi-ia32' and not 'grub-efi-ia32-bin'?

**Comment by mepradeepkr** [comment]
sir,
currently i am using windows.. i never used any Linux distribution before

steps that i followd--

1. I downloaded "UBUNTU MATE.iso" provided by you on github
2. Changed UFEI Settings
3. Create a bootable pen drive using "rufus" software in windows.
4. Booted this pen drive to my computer......clicked on install ubuntu
MATE(second option perheps)
5. Then i installed it without dual booting windows.."erase everything and
install  fresh ubuntu Mate" on my 32GB emmc storage of laptop
6. meanwhile installing at the step "System install" -> "Hardware_check"
the installation stopped and showed me that error...
7. Closeing that error window, Currently ubuntu mate was running on my
computer....but after shutdown..plugling out bootable usb...


When I restarted that PC Again I was in UFEI options..ubuntu never booted
again--

I stucked there, no one have computer near me "i had to go Cyber cafe to
make a win32 bootable pen drive  :) :) "

**Comment by mepradeepkr** [comment]
reply sir-- please.....

**Comment by sundarnagarajan** [comment]
I am sorry for the bad experience you have. Rest assured that you will have the RDP Thinbook running Linux perfectly in a couple of days at most!

Sorry for the delay. It is nearly 3 AM here. I will reply tomorrow morning. Do not worry - I have utils (which are on the ISO under /root/scripts) that can help you make your earlier installation bootable.

**Comment by mepradeepkr** [comment]
okk..sir

**Comment by sundarnagarajan** [comment]
Pradeep,

Once again, sorry for the poor experience you had. I believe the problems you faced are due to one or more of the following:

- Poor code in the Linux distribution (Ubuntu Mate) that is failing when it should not, or providing the WRONG error message
- Distribution not detecting at the time of STARTING the installer that this is a UEFI system and warning / asking the user to create an EFI partition and / or automatically using the EFI partition when it exists (as it SHOULD on the RDP Thinbook emmc disk)

That being said, if the installer got all the way to the stage you indicated, the installation CAN be recovered using some tools. This is apart from doing a complete reinstall successfully, which is ALSO possible - but we will go there only if you are NOT able to recover the previous installation.

## Important note
**You should NEVER need to get a Win32 bootable pen drive.**

Most Linux distributions - including Ubuntu Mate, Xubuntu and Ubuntu (regular) - provide a 'Live CD' mode, where you can start and use Linux without installing at all. That mode is chosen from the menu which you see when you boot from the ISO and is usually called something like ```Try Ubuntu without installing```. Windows has **never had** such a mode - all you get with a 'Win32 bootable pen drive' is a way to **start the Windows installer**. You can't use the 'Win32 bootable pen drive' to do anything useful - like access the Internet, learn new things etc.

That is the mode you should **ALWAYS** try first before trying to install. Despite any testing I have done, this will allow you to be be clear that all the hardware (Wifi, Bluetooth, display, sound etc) all work perfectly in that distribution on the machine / hardware you are using.

The ```Try Ubuntu without installing``` mode is also a very good way to play around with Linux without installing. You get **everything** that Linux can do **except** that the system will not 'remember' changes you made if you reboot. If you have not used Linux before, this is also a very good way to learn a bit about Linux. Once you know the basics, you can do the install.

I have done quite a bit of work to make sure that **all the hardware** works perfectly in the 'Live CD' mode ( ```Try Ubuntu without installing```). I highly recommend using that to become familiar with Linux first.

**Please let me know whether you previously used the** ```Try Ubuntu without installing``` **mode, or did you directly choose the** ```Install Ubuntu Mate``` **menu entry when booting?**

Personally I have never tested the ```Install Ubuntu Mate``` mode.**

## Recovering your previous installation
I note from your email that you are very new to Linux. This will make it a little more difficult for you to follow the instructions that follow. Please try your best to type the commands EXACTLY as below.

First I need a little information about how you (or the installer automatically) partitioned your emmc disk during the install.

## Steps

1. Insert the bootable **Linux ISO USB** disk that you created with Ubuntu Mate
2. Turn on the RDP Thinbook, and as soon as the RDP symbol appears, press F7
3. Choose your USB disk from the menu - it will look something like 'UEFI: disk_brand_model'. This is **NOT** the entry labelled 'ubuntu' - if such an entry appears
4. If your USB disk does not appear, press Ctrl-Alt-Del and **AGAIN** press F7 as soon as the RDP symbol appears - your disk **should** apear at least the second time
5. Boot into Ubuntu Mate choosing ```Try Ubuntu Mate without Installing```
6. Once inside Ubuntu Mate open a **Terminal** by using the menu Applications --> 
    System Tools --> Mate Terminal
    Read and follow the following instructions very carefully:

    ```
    sudo parted /dev/mmcblk0 print
    ```

    The output of the parted command should look something like this:

    ```
    Model: MMC NCard (sd/mmc)
    Disk /dev/mmcblk0: 31.0GB
    Sector size (logical/physical): 512B/512B
    Partition Table: gpt
    Disk Flags: 
    
    Number  Start   End     Size    File system     Name  Flags
     5      17.4kB  1049kB  1031kB                  bios  bios_grub
     1      1049kB  106MB   105MB   fat16           EFI   boot, esp
     2      106MB   21.6GB  21.5GB  ext4            root
     3      21.6GB  24.8GB  3221MB  linux-swap(v1)  swap
     4      24.8GB  31.0GB  6236MB                  data
    ```

7. Open Firefox from the menu Applications --> Internet --> Firefox Web Browser
8. Log into your github account
9. Copy the output from the terminal and paste it into a reply to this issue

## Why do I need this?
The goal is to run the script /root/remaster/scripts/make_bootable.py
that script needs two parameters:
1. The disk device - we know this - it is /dev/mmcblk0
2. The root partition - that I should be able to figure out from the output of parted

**Comment by sundarnagarajan** [comment]
Pradeep,

No reply for nearly a week. If I do not hear back, I will be closing this issue.

**Comment by mepradeepkr** [comment]
sorry its Because of my exam......

I will reply after 4 days.....so sorry

**Comment by mepradeepkr** [comment]
close this issue i m going to purchase a new laptop

**Comment by sundarnagarajan** [comment]
Issue closed - reporter never responded with details

**Comment by mepradeepkr** [comment]
![01](https://user-images.githubusercontent.com/20892010/32958877-c51bf890-cbe5-11e7-892d-0aedb3b86e73.jpg)
![02](https://user-images.githubusercontent.com/20892010/32958880-c640c444-cbe5-11e7-9ed5-092eaa3ed5aa.jpg)
sir, that was the problem 
when i was installing..

**Comment by mepradeepkr** [comment]
plese sir , reply me....

**Comment by mepradeepkr** [comment]
please sir reply me

**Comment by sundarnagarajan** [comment]
What reply do you expect? Did you read and understand the earlier [detailed response](https://github.com/sundarnagarajan/rdp-thinbook-linux/issues/8#issuecomment-331663968) I provided? Have you provided the answers I requested? Until then, I am afraid there is little I can do.

Also read and understand the [very first FAQ](https://github.com/sundarnagarajan/rdp-thinbook-linux/blob/master/faq.md#how-to-report-a-problem). Unless your problem report contains the minimum information I haev asked for, please do not expect a response from me.

**Comment by sundarnagarajan** [comment]
I thought you said 'close this issue i m going to purchase a new laptop' on [Oct-09](https://github.com/sundarnagarajan/rdp-thinbook-linux/issues/8#issuecomment-335111523)? I have already closed this issue.

**Comment by tanmaydwivedi** [comment]
->Having same problem "the grub-efi-ia32 package failed to install into /target/, without the GRUB bootloader, the installed system will not boot"
->Used your pre-created iso Ubuntu 16.04.3 LTS Ubuntu flavor & created the bootable pendrive using "Rufus"
This error occured while in near completion of ubuntu installation on my 1430p RDP thinbook laptop.

Model: MMC NCard (sd/mmc)
Disk /dev/mmcblk0: 31.0GB
Sector size (logical/physical): 512B/512B
Partition Table: gpt
Disk Flags: 

Number  Start   End     Size    File system     Name                  Flags
 1      1049kB  538MB   537MB   fat32           EFI System Partition  boot, esp
 2      538MB   29.0GB  28.4GB  ext4
 3      29.0GB  31.0GB  2067MB  linux-swap(v1)

Ask any other required details, i'l try to reply asap.
